### ISSUE TITLE
Http request to graphql API of prismic

### ISSUE THREAD

**Issue by MartCube** [nuxt-modules/prismic#148]
As the title says, I was wondering can we do something like this with prismic.
In this [Strapi module](https://strapi.nuxtjs.org/strapi#graphqldata) they offer us a simple way to querry using graphql.

**Comment by lihbr** [comment]
Hey @MartCube, thanks for the suggestion!

Indeed that would be an interesting thing to have. We'll try to consider that while keeping in mind it should have no/minimal impact on users not using GraphQL ☺️

**Comment by lihbr** [comment]
Hey there, not sure we'll move on with that, so I'll close this issue. Feel free to reopen if you want to give a shot at implementing it though.
