### ISSUE TITLE
Nuxt Image + Prismic Usage

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt-modules/prismic#168]
Hello 👋,

I tried to set up prismic `"@nuxtjs/prismic": "^3.0.0-rc.0"` with `"@nuxt/image-edge": "^1.0.0-27657146.da85542"` but it doesn't seems to work at all. My `nuxt.config.ts` file :

```ts
import { defineNuxtConfig } from 'nuxt'
export default defineNuxtConfig({
  modules: [
    '@nuxt/image-edge',
    '@nuxtjs/prismic'
  ],
  prismic: {
    endpoint: 'my-repo-Id,
    preview: false,
    toolbar: true
  },
  image: {
    provider: 'prismic',
    domains: ['prismic.io']
  }
})
```

and in the my `.vue` files :

```vue
<template>
          <nuxt-picture
            src="/c-1-910w.webp"
            width="910"
            height="1365"
            sizes="sm:518px, 2xl:910px"
            :img-attrs="{
              class: 'img-unit',
              alt: `Alternative text`
            }"
          />
</template>
```

**Comment by lihbr** [comment]
Hey there,

Looks like you're trying to use a local image with Nuxt Image Prismic provider set as the default provider.

In such case I think you need to specify an explicit provider:
```vue
<nuxt-picture
	  provider="ipx"
	  src="/c-1-910w.webp"
	  width="910"
	  height="1365"
	  sizes="sm:518px, 2xl:910px"
	  :img-attrs="{
	    class: 'img-unit',
	    alt: `Alternative text`
	  }"
/>
```

Let me know :)

**Comment by BenjaminOddou** [comment]
Hello @lihbr,

In fact I am trying to use prismic images directly but maybe my configuration is not correct. 🤔

**Comment by lihbr** [comment]
Sure, my bad!

In this case, you'll need to provide your image field's URL as the src, something like this: 

```vue
<nuxt-picture
	:src="doc.data.my_image.url"
	width="910"
	height="1365"
	sizes="sm:518px, 2xl:910px"
	:img-attrs="{
		class: 'img-unit',
		alt: `Alternative text`
	}"
/>
```

**Comment by BenjaminOddou** [comment]
hello @lihbr,

with the following configuration 
```vue
          <nuxt-picture
            src="/c-1-910w.webp"
            width="910"
            height="1365"
            sizes="sm:518px, 2xl:910px"
            :img-attrs="{
              class: 'img-unit',
              alt: `Alternative text`
            }"
          />
```
I have this error message
```shell
GET https://images.prismic.io/c-1-910w.webp?fm=webp&fit=crop&q=80&loading=lazy&w=910&h=1365 [HTTP/2 404 Not Found 279ms]  
```
and with your suggestion, TS is throwing me `Property 'doc' doesn't exist for the type ComponentInternalInstance` and VUE is throwing me errors as well `Parsing error: ',' expected.`.

I was wondering if there is nothing to change in my nuxt.config.ts file or something to enable with prismic. I mean is there any token/security stuff to manage in order to access images ?

**Comment by BenjaminOddou** [comment]
@lihbr, 

After digging a bit I found that there is two things missing in the generated URLs.

what I should have :

```
https://images.prismic.io/<REPO NAME>/<ID OF IMAGE>_c-1-910w.webp fm=webp&fit=crop&q=80&loading=lazy&w=910&h=1365
```

Also is there a secure way to call these images ? I know that there is a way to generate acess tokens but how to use them in this kind of config ?

**Comment by lihbr** [comment]
OK, thanks for providing more info!

When using Nuxt image with Prismic you **cannot** use only an image name. That's because the component cannot guess your repository name and image hash (ID) as you noticed.

To use Nuxt image with Prismic you need to pass it the full image URL served by Prismic available in Prismic image fields returned by the API.

Here's a tutorial about using Nuxt Image with Prismic: https://prismic.io/blog/nuxt-image-is-out-so-is-its-prismic-integration, it's relying on Nuxt 2 integration but the logic should remain the same.

> Also is there a secure way to call these images ? I know that there is a way to generate acess tokens but how to use them in this kind of config ?

Unfortunately signing assets is not available on images served by Prismic. It is [a feature of imgix](https://docs.imgix.com/setup/securing-assets), our image provider, but it is not made available as of writing this, but I'll forward your feedback :)

**Comment by BenjaminOddou** [comment]
@lihbr,

So if I am understanding correctly,
I have to provide the `repo-name` + `hash` for each image. Is there a way to dynamically define these urls? If I have 100 images in a gallery do I have to search for each `hash` manually, copy and paste it into each `src` fields ??

I can see in your demo that you added :

```vue
<nuxt-img v-if="item.image.url" :src="item.image.url" />
```

But I don't understand this piece of code 😅

**Comment by lihbr** [comment]
> So if I am understanding correctly, I have to provide the `repo-name` + `hash` for each image.

No you don't, generally you're not expected to grab image URLs from your library directly (you can, but it'd be manual then)

To automate it, the flow goes like this (this is a rough outline of it, check out [the Prismic doc](https://prismic.io/docs/technologies/nuxt) for a comprehensive tutorial):
1. You define your content type on Prismic, some may feature image fields
2. You create documents with these content types
3. You query them with Nuxt ([example with Nuxt 3](https://v3.prismic.nuxtjs.org/guides/basics/fetching-content))
4. Then inside your template, you can feed image field's URLs from your documents to Nuxt Image like in the snippet you quoted:

```html
<nuxt-img v-if="item.image.url" :src="item.image.url" />
```

This snippet basically checks if the image field is filled (available) by checking for a truthy `url` property, if so, it displays the component and provides it with the said `url` property to display the image.

**Comment by BenjaminOddou** [comment]
@lihbr , thank you for this precision! 

However may I ask you if `slicemachine` is needed for this ? Because it's not working with Nuxt 3 for now.

```shell
✔ Project configured! Ready to start
⠏ Installing Slice MachineError! Command failed: npm install --save @nuxtjs/prismic @prismicio/slice-simulator-vue
```

**Comment by lihbr** [comment]
Slice is not "needed" indeed, and does not support Nuxt 3 officially yet indeed (you'd have to hack your way around to get it to work with Nuxt 3). With that in mind I'd recommend sticking to the classic custom type editor available online for now in that use case.

**Comment by BenjaminOddou** [comment]
Hello @lihbr

Sorry for requiring your help again but I am really struggling with the module. I am getting this error (testing my build locally):

```shell
Blocked a frame with origin "https://<REPO_ID>.prismic.io" from accessing a frame with origin "http://<IP_ADRESS>:3000".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
```

**Comment by lihbr** [comment]
It looks like you didn't replace `<REPO_NAME>` with your own Prismic repository name here.

Which tutorial did you follow?

**Comment by BenjaminOddou** [comment]
I followed [this guide](https://v3.prismic.nuxtjs.org/guides/basics/fetching-content). I set up my repo name/Id in the `nuxt.config.ts` file: 

```ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
modules: ['@nuxtjs/prismic'],
prismic: { endpoint: 'my_repo_id' },
image: {
  provider: 'prismic',
  prismic: {}
}
})
```

**Comment by lihbr** [comment]
Alright, I'm sorry but I just don't have enough information to help you past that point.

Please provide a comprehensive reproduction as a .zip folder in that thread and explain clearly the error(s) you are experiencing.
