### ISSUE TITLE
The requested module '@nuxt/kit' does not provide an export named 'addAutoImport'

### ISSUE THREAD

**Issue by brunodeangelis** [nuxt-modules/prismic#172]
### Versions

- nuxt: 3.0.0
- @nuxtjs/prismic: 3.0.0-rc.1
- node: 16.16.0

### Reproduction

[https://stackblitz.com/edit/nuxt3-prismic-bug](https://stackblitz.com/edit/nuxt3-prismic-bug)

### Steps to reproduce

Fresh install of Nuxt 3 Stable, add Nuxt Prismic module rc 1.

Any help greatly appreciated.

**Comment by lihbr** [comment]
Hi there, thanks for the heads up!

The Nuxt team published some last breaking changes yesterday leading to that issue. This should be fixed with `@nuxtjs/prismic@3.0.0-rc.2`

Let me know if anything! Feel free to reopen as needed :)
