### ISSUE TITLE
Previews not working

### ISSUE THREAD

**Issue by davidmarkl** [nuxt-modules/prismic#176]
### Versions

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `css`, `modules`, `tailwindcss`, `prismic`, `nitro`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/prismic@3.0.0-rc.2`
- Build Modules:    `-`
------------------------------

Chrome 109.0.5414.120

### Description

I did it all just like described in the docs. I dont use a `/preview` page, I provide a working linkResolver, I set up a dev and a production preview in my prsimic repo, I use the plugin config defaults...

Whenever I click the preview button I get to the /preview loading page and then I get properly redirected through the linkResolver but the content is still "old". I tried SSR, SPA, SSG but nothing worked. Not even the dev preview.

When I monitor the requests it looks totaly fine. The document with the new data even arrives in my network tab.

**Comment by lihbr** [comment]
Hey David, thanks for opening an issue!

Can you share a minimal reproduction of your setup (a StackBliz would be perfect), that would help speed up the troubleshooting process~

**Comment by lihbr** [comment]
Closing as stale, feel free to reopen if you want to continue troubleshooting your issue!
