### ISSUE TITLE
Prismic preview not working with SSG

### ISSUE THREAD

**Issue by arthurmchr** [nuxt-modules/prismic#191]
### Versions

- nuxt: v3.4.3
- @nuxtjs/prismic: v3.0.0-rc.4
- node: v18.16.0

### Reproduction

<details open>
<summary>nuxt.config.js</summary>
<br>

```
export default defineNuxtConfig({
  modules: ['@nuxtjs/prismic'],
  prismic: {
    endpoint: 'myprismicendpoint',
    linkResolver: '~/link-resolver.js',
  },
})
```

</details>

<details open>
<summary>pages/index.vue</summary>
<br>

```
<script setup>
const { client } = usePrismic()

const { data: home } = await useAsyncData('homepage', () =>
  client.getSingle('homepage')
)
</script>

<template>
  <div>
    <span>{{ home.data.title }}</span>
  </div>
</template>
```

</details>

### Steps to reproduce
I have a minimal setup of a single page site that I am trying to preview. I run `npm run generate`, then on prismic, after configuring a preview endpoint, try to preview the page on the generated content. I have configured `link-resolver.js` (for the example, always return `/`.

### What is Expected?
I should see my draft content

### What is actually happening?
Only the old published content is visible. It works well with the development version, before running `npm run generate`.

On prismic, I have configured 2 preview endpoints, reaching 2 different ports on my localhost (3000 for dev version, 8000 for SSG)

**Comment by lihbr** [comment]
Hey there, thanks for contributing!

How are you configuring the preview endpoint on Prismic? By default with the module, you should point it towards `/preview`

**Comment by arthurmchr** [comment]
Hi Lucie,
Thanks for your answer.

Yes that is what I have set as my prismic preview route, with domain set on the port serving my generated content. (through `npm run preview`)
I just tested a fresh install with nuxi, the only things I have added is the link-resolver.js, @nuxt/prismic module (3.0.0-rc.6) and add a page file as presented above in the pages folder.
Still not working :(

In the log (of npm run preview), I see the preview request :
`HTTP  15/05/2023 17:37:31 ::1 GET /preview?token=https%3A%2F%2F myprismicendpoint.prismic.io%2Fpreviews%2FZFdwOhEAACIAq3bK%3AZFdwQhEAACAAq3bv%3FwebsitePreviewId%3DZFdyVxEAACAAq4Bp&documentId=ZFdwNhEAACIAq3a1` but only old content, not draft one.

**Comment by arthurmchr** [comment]
Here is a reproduction of the project : [https://stackblitz.com/edit/github-srs7pp?file=nuxt.config.ts](https://stackblitz.com/edit/github-srs7pp?file=nuxt.config.ts).
I used the Nuxt 3 starter for stackblitz.

If I run `npm run generate`, then serving the generated content `.output/public` on port `8000` and set up the prismic preview endpoint to `/preview` on `http://localhost:8000` it does not work.

**Comment by lihbr** [comment]
Thanks for sharing more! I'll keep investigating :relaxed:

**Comment by lihbr** [comment]
Hey there, thanks again for providing comprehensive details! I managed to reproduce the issue, track it down, and publish a fix as part of `rc.7`: https://github.com/nuxt-modules/prismic/blob/v3.0.0-rc.7/CHANGELOG.md#300-rc7-2023-05-16

Can you try again with this version and let me know about it?

The Nuxt 3 module should go out of RC next week 🎉

**Comment by arthurmchr** [comment]
Hey !
Thanks for your investigation.

The minimal project preview is now working as expected, but it looks like a more complex project still not.
Trying to reproduce it on a minimal project, send you a new stackblitz when it's ready :)

**Comment by lihbr** [comment]
Weird 🤔 One thing I tried while working on it is adding a log to the async data, to know if it's even called after launching the preview session, maybe this can give you some hint.

Otherwise if you can share a GitHub or anything, happy to install something bigger.

**Comment by jcmidia** [comment]
Hello! I'm also having problems with the preview on Nuxt 3. I just bump the prismic package to rc7 but it still doesn't work. When I click on the preview link from Prismic CMS it opens the link and redirects to the home page.
On the console log I see the following request:

http://localhost:3000/preview?token=https%3A%2F%2Ffuturing-peace.prismic.io%2Fpreviews%2FZGeowRAAACEApRTV%3FwebsitePreviewId%3DZGelQxAAACEApQ70&documentId=ZDhNAREAACQAhtrc

**Comment by arthurmchr** [comment]
Hey there !

After some research, I finally found my problem; I am trying to set a new reactive variable from the data object I get as a result of `useAsyncData` query.

It does not work in SSG, but if I directly use the data object it does.

```js
const { data: homepage } = await useAsyncData('homepage', () =>
  client.query({ query: GET_HOME_PAGE, variables })
);

const page = ref(homepage.value.data);
```

and in template :
```
{{ page.title }} // does not work after generating a static version but works in Dev
{{ homepage.data.title }} // works
```

I assume that my problem cames from data reactivity.
BTW, using `rc.7` without "proxy" variable works.

**Comment by arthurmchr** [comment]
Thanks @lihbr, it works as expected with `computed` :)

**Comment by jcmidia** [comment]
@lihbr thank you so much! Now I can see the changes live on my page, it is just when I click on the preview link in Prismic it always takes me to the home page, then if I navigate to About, for example, I can see the changes on the page. Do I need to have all my pages listed on the link-resolver.js? This is what I have right now:

`export default (doc) => {
  if (doc.type === "page") {
    return `/${doc.uid}`;
  }
};
`

I will try to create a small project to test it better like arthur did and if it doesn't work I will share it here. Thanks a lot!

**Comment by jcmidia** [comment]
I just got my problem solved by using the Route Resolver :)
