### ISSUE TITLE
No runtime confuguration for the pugin

### ISSUE THREAD

**Issue by sylr** [nuxt-modules/prismic#192]
### Versions

- nuxt: 
- @nuxtjs/prismic: v3.0.0-rc.5
- node:v3.1.1

### Reproduction

We have a nuxt project which is running 3 instances (dev, test prod). We are building a docker container that we are running in a kubernetes cluster and we use ENV vars to configure nuxt at runtime based on the env.

### What is Expected?

We expect to be able to configure the nuxt-prismic plugin at runtime so what we can change the prismic endpoint using env vars.

### What is actually happening?

nuxt-prismic is only configurable at build time.

**Comment by lihbr** [comment]
Should be fixed in `rc.6`, thanks!
