### ISSUE TITLE
asHTML serializer doesn't work

### ISSUE THREAD

**Issue by luca-smartpricing** [nuxt-modules/prismic#197]
`asHTML` serializer doesn't work on nuxtjs/prismic: v3.0.0

### Versions

- nuxt: v3.5.3
- @nuxtjs/prismic: v3.0.0
- node: 18.16.0

### Reproduction
https://stackblitz.com/edit/nuxt-starter-pzgnkr?file=app.vue

**Comment by lihbr** [comment]
Oh yeah, my bad for the example, went too fast, updated it ☺️
