### ISSUE TITLE
slicemachine Error : "too many open files"

### ISSUE THREAD

**Issue by kaboume** [nuxt-modules/prismic#201]
### Versions

- nuxt: 3.6.5
- @nuxtjs/prismic: 3.0.1
- node: 16.18.0

Hi,
I'm working on a big website, under Nuxt3 + Prismic, with lots of slices (around 80) and pages (around 30)? Until yesterday, everything was working fine but when I added a new slice or page yesterday, my slicemachine no longer works.
The interface is displayed well with the pages and slices but it tells me that I am not logged in and even after having logged back in.
And when I check the changelog it says 'Could not fetch release notes. Find out more on GitHub'

In the console I have a 500 error on http://localhost:9999/_manager and the returned message is
��error��name�Error�message�gEMFILE: too many open files, open 'C:\DEV\my-project\node_modules\slice-machine-ui\package.json'

What to do ?

**Comment by lihbr** [comment]
Closing as this should be fixed now, feel free to reopen if anything!
