### ISSUE TITLE
Getting Started documentation is missing types generation step

### ISSUE THREAD

**Issue by zrisher** [nuxt-modules/prismic#206]
### Versions

- nuxt: 3.10.3
- @nuxtjs/prismic: 3.1.0
- node: 20.9.0

### Steps to reproduce

- Create a new repo with the latest Nuxt
- Follow the steps on https://prismic.nuxtjs.org/get-started

### What is Expected?

No Typescript errors occur.

### What is actually happening?

Typescript complains that `prismic` is not a known key for the option argument to `defineNuxtConfig`.

### Suggestion solution

Add a step in the Getting Started documentation between steps 1 and 2 that suggests running nuxt's `postinstall` task. For me this was `npm run postinstall`, which in turn calls `nuxt prepare`, regenerating the types and fixing the error.

**Comment by kgonzales1193** [comment]
still didn't fix the problem for me after running `npm run postinstall`

**Comment by kgonzales1193** [comment]
i tried creating a new repo run post install and yet, i am still getting the missing types. 
![image](https://github.com/nuxt-modules/prismic/assets/117622808/4c60945b-69a0-4b65-8736-34258ae751f6)

**Comment by lihbr** [comment]
Hey @zrisher, sorry for the delay getting back to you, I've updated the documentation to use `nuxi module add prismic` so people stop facing this issue by default ☺️

@kgonzales1193, I was not able to reproduce your issue so far but it looks like an issue maybe related with Vue language server (wild guess), do you have the same issue on a plain Nuxt project (`npx nuxi@latest init`), or is it just after initializing Slice Machine?

**Comment by zrisher** [comment]
@lihbr Thank you!
