### ISSUE TITLE
Wrong type for preview config key

### ISSUE THREAD

**Issue by simonmaass** [nuxt-modules/prismic#215]
### Versions

- nuxt:  3.12.2
- @nuxtjs/prismic:  3.3.1
- node:  20.11.1

### Steps to reproduce

Type in docs:
https://prismic.nuxtjs.org/configuration

<img width="725" alt="image" src="https://github.com/nuxt-modules/prismic/assets/32599710/b9917301-dfc7-43c4-8c41-6a0e6b71fedf">

Type in IDE:
<img width="395" alt="image" src="https://github.com/nuxt-modules/prismic/assets/32599710/ed6c0f42-17b1-452e-84e0-9ae3ba02182c">

**Comment by lihbr** [comment]
Thanks for the heads up! Should be good in `v3.3.2` 🚀
