### ISSUE TITLE
Failed to load Parser5 file 

### ISSUE THREAD

**Issue by timothejoubert** [nuxt-modules/prismic#217]
## Bug description
<img width="261" alt="image" src="https://github.com/user-attachments/assets/d0a151c4-783c-4a92-ac6a-a6d796be5968">

Parser5 don't generate index.js.map file

## Environment
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      modules, prismic, devtools, compatibilityDate
- Runtime Modules:  @nuxtjs/prismic@3.3.2
- Build Modules:    -
------------------------------

## Reproduction
Can be reproduce on your [online playground](https://stackblitz.com/github/nuxt-modules/prismic/tree/master/examples/minimal?file=pages/index.vue)

## Logs
```
[19:51:08]  WARN  Failed to load source map for /home/projects/kkvillvwkz.github/node_modules/parse5/dist/index.js.
Error: An error occurred while trying to read the map file at index.js.map
ENOENT: no such file or directory, open '/home/projects/kkvillvwkz.github/node_modules/parse5/dist/index.js.map'

[19:51:09]  WARN  Failed to load source map for /home/projects/kkvillvwkz.github/node_modules/parse5/dist/parser/index.js.
Error: An error occurred while trying to read the map file at index.js.map
ENOENT: no such file or directory, open '/home/projects/kkvillvwkz.github/node_modules/parse5/dist/parser/index.js.map'

[19:51:09]  WARN  Failed to load source map for /home/projects/kkvillvwkz.github/node_modules/parse5/dist/tree-adapters/default.js.
Error: An error occurred while trying to read the map file at default.js.map
ENOENT: no such file or directory, open '/home/projects/kkvillvwkz.github/node_modules/parse5/dist/tree-adapters/default.js.map'

[19:51:09]  WARN  Failed to load source map for /home/projects/kkvillvwkz.github/node_modules/parse5/dist/serializer/index.js.
Error: An error occurred while trying to read the map file at index.js.map
ENOENT: no such file or directory, open '/home/projects/kkvillvwkz.github/node_modules/parse5/dist/serializer/index.js.map'
```

## Additional context
Revert Prismic version don't fix this bug. 
This issue break my HMR in my app.
Does anyone have a temporary solution for this?

**Comment by lihbr** [comment]
Hey @timothejoubert, thanks for contributing!

We're aware of this issue with `parse5`, it's also impacting [`@nuxt/content`](https://github.com/nuxt/content/issues/2663) and [`@nuxtjs/mdc`](https://github.com/nuxt-modules/mdc). The issue [has already been reported to `parse5`](https://github.com/inikulin/parse5/issues/1194), we're hoping they will be able to release a fix soon.

On our end we'll release a fix tomorrow to remove our dependency on `parse5`, which should silence the warning on your end and make HMR work again.

Thanks for your understanding!

**Comment by lihbr** [comment]
Hi there, this issue should be fixed with the latest version of `@prismicio/client`.

You should be able to get it using `npm update @prismicio/client@`, or by removing your lock file and node modules folder and reinstalling your project again.

Thanks for your patience! 🙏 Feel free to reopen if you still experience the same trouble.
